### ISSUE TITLE
Not real communism

### ISSUE THREAD

**Issue by krvajal** [jokteur/python_communism#4]
You need to make everything perform poorly and slow to be closer to real communism. Otherwise, you got the wrong idea of what communism is.

**Comment by jokteur** [comment]
As stated in the footnotes of _our_ readme, we see that: 

> not all classes are born equal. It is not possible to do a complete communist revolution without breaking the language. This is why there are elites (like the __builtins__) which are more equal than all of the others.

and also that

> the communist revolution does not prevent future classes to be equal to all others. Classes declared after the communism.revolution() will not follow the communism rule.

I hope it answer your concern.

**Comment by mniami** [comment]
I suppose, he thoughts about slowing down all python code by increasing CPU usage, introducing waitings for resources, missing available devices, breaks with the network connections, slowing it down much.

In the same time, introduce memory leaks, military night hours - at night none of the process can work, wasting cpu without calculating a value at the end, empty lists, collections and sets, dictionaries which keys are censored, and probably much more.

That's a real communism ideology consequences.

**Comment by krvajal** [comment]
You nailed it @mniami

**Comment by claudiodriussi** [comment]
But remember, to achieve the **real communism** you have to consider that:

social_classes in abstract_class_concept == True
python_classes in abstract_class_concept == True
python_classes in social_classes == False

All our efforts are aimed to let (python_classes in social_classes) become True

**Comment by jokteur** [comment]
You are right.

However, this is only the package for the communist revolution, it does not directly implement communist ideology consequences.

However, I suppose starving dict and set to be able to only hold one class would already introduce some problems and waiting times for future programs. It is already a first step.

**Comment by HacKanCuBa** [comment]
> You need to make everything perform poorly and slow to be closer to real communism. Otherwise, you got the wrong idea of what communism is.

Meanwhile, in capitalism...

**Comment by VitAndrGuid** [comment]
> > You need to make everything perform poorly and slow to be closer to real communism. Otherwise, you got the wrong idea of what communism is.
> 
> Meanwhile, in capitalism...

We got a commie over here

**Comment by tlaziuk** [comment]
it should also lead to starvation of the process where it's used and kill it's children, not sure if I should create separate PRs for those two missing features though

**Comment by perfecto25** [comment]
> it should also lead to starvation of the process where it's used and kill it's children, not sure if I should create separate PRs for those two missing features though

i tried using this communism class, but it keeps starving my desktop of resources 

also seems to kill all memory

**Comment by heipiao233** [comment]
Did you read any book about REAL COMMUNISM from people such as Marx, Lenin? If you don't know what is COMMUNISM, please don't say you know about it.

**Comment by nosknut** [comment]
Are you contradicting our glorious leader? ...

**Comment by krvajal** [comment]
@heipiao233 I did read all of that, but even more I lived in a communist country for more than 20 years, so I am pretty sure I know what I am talking about. And by the way, China isn't communist, or ask your friend Marx to see what he says

**Comment by heipiao233** [comment]
Yes, I know about that.
